import type { Category } from '../types';

export const DEFAULT_CATEGORIES: Category[] = [

  // ══════════════════════════════════════════════
  // 毎日2回（日勤・夜勤）: ER救急カート薬品
  // ══════════════════════════════════════════════
  {
    id: 'cat-er-cart-drug1',
    name: '救急カート薬品 1室用（赤）',
    frequency: 'daily2',
    items: [
      { id: 'ecd1-01', name: 'ボスミン注 1mg/1ml',          standardStock: 5  },
      { id: 'ecd1-02', name: 'ドブタミン 100mg/5ml',        standardStock: 3  },
      { id: 'ecd1-03', name: 'ドパミン塩酸塩 100mg/5ml',    standardStock: 3  },
      { id: 'ecd1-04', name: 'ジギラノゲンC 0.4mg/2ml',     standardStock: 2  },
      { id: 'ecd1-05', name: 'アトロピン注 0.5mg/1ml',      standardStock: 6  },
      { id: 'ecd1-06', name: 'アドレナリン 1mg/1ml',        standardStock: 10 },
      { id: 'ecd1-07', name: 'エフェドリン 40mg/1ml',       standardStock: 1  },
      { id: 'ecd1-08', name: 'ワソラン注 5mg/2ml',          standardStock: 3  },
      { id: 'ecd1-09', name: 'ノルアドレナリン 1mg/1ml',    standardStock: 3  },
      { id: 'ecd1-10', name: 'サンリズム 50mg/5ml',         standardStock: 2  },
      { id: 'ecd1-11', name: 'キシロカイン２% 100mg/5ml',   standardStock: 5  },
      { id: 'ecd1-12', name: 'メイロン２０ 20ml',           standardStock: 2  },
      { id: 'ecd1-13', name: 'ネオシネジンコーワ 1ml',      standardStock: 1  },
      { id: 'ecd1-14', name: 'アミオダロン 150mg/3ml',      standardStock: 3  },
      { id: 'ecd1-15', name: 'カルチコール 8.5%/5ml',       standardStock: 3  },
      { id: 'ecd1-16', name: '生理食塩液 20ml',             standardStock: 5  },
      { id: 'ecd1-17', name: 'メイロン２５０ 250ml',        standardStock: 1  },
      { id: 'ecd1-18', name: 'ソルアセトF 500ml',           standardStock: 1  },
      { id: 'ecd1-19', name: '塩酸ドパミンキット 200ml',    standardStock: 1  },
      { id: 'ecd1-20', name: 'ソルデム１ 500ml',            standardStock: 1  },
      { id: 'ecd1-21', name: 'ソセゴン 15mg/1ml',           standardStock: 5  },
      { id: 'ecd1-22', name: 'ホリゾン 10mg/2ml',           standardStock: 5  },
    ],
  },
  {
    id: 'cat-er-cart-drug2',
    name: '救急カート薬品 2室用（ピンク）',
    frequency: 'daily2',
    items: [
      { id: 'ecd2-01', name: 'アドレナリン 1mg/1ml',        standardStock: 10 },
      { id: 'ecd2-02', name: 'プロタノールL注 0.2mg/1ml',   standardStock: 3  },
      { id: 'ecd2-03', name: 'アトロピン注 0.5mg/1ml',      standardStock: 5  },
      { id: 'ecd2-04', name: 'キシロカイン２% 100mg/5ml',   standardStock: 5  },
      { id: 'ecd2-05', name: 'ボスミン注 1mg/1ml',          standardStock: 5  },
      { id: 'ecd2-06', name: 'アトロピン硫酸塩 0.5mg/1ml',  standardStock: 5  },
      { id: 'ecd2-07', name: 'ワソラン注 5mg/2ml',          standardStock: 3  },
      { id: 'ecd2-08', name: 'フルマゼニル 0.5mg/5ml',      standardStock: 2  },
      { id: 'ecd2-09', name: '生理食塩液 20ml',             standardStock: 5  },
      { id: 'ecd2-10', name: 'ブチルスコポラミン 20mg/1ml', standardStock: 2  },
      { id: 'ecd2-11', name: 'フェノバール 100mg/1ml',      standardStock: 3  },
      { id: 'ecd2-12', name: 'ニカルジピン 2mg/2ml',        standardStock: 2  },
      { id: 'ecd2-13', name: 'ジギラノゲンC 0.4mg/2ml',     standardStock: 2  },
      { id: 'ecd2-14', name: 'カルチコール 8.5%/5ml',       standardStock: 3  },
      { id: 'ecd2-15', name: 'ネオシネジンコーワ 1ml',      standardStock: 1  },
      { id: 'ecd2-16', name: 'メトクロプラミド 10mg/2ml',   standardStock: 3  },
      { id: 'ecd2-17', name: 'ソル・メドロール 125mg',      standardStock: 2  },
      { id: 'ecd2-18', name: 'メイロン２０ 20ml',           standardStock: 2  },
      { id: 'ecd2-19', name: '注射用水 20ml',               standardStock: 2  },
      { id: 'ecd2-20', name: '５０%ブドウ糖 20ml',          standardStock: 2  },
      { id: 'ecd2-21', name: 'ソルアセト 500ml',            standardStock: 4  },
      { id: 'ecd2-22', name: 'ソルデム１ 500ml',            standardStock: 1  },
      { id: 'ecd2-23', name: 'メイロン２５０ 250ml',        standardStock: 1  },
      { id: 'ecd2-24', name: '塩酸ドパミンキット 200ml',    standardStock: 2  },
      { id: 'ecd2-25', name: '生理食塩液 100ml',            standardStock: 1  },
    ],
  },
  {
    id: 'cat-er-stock-a',
    name: '処置室ストック薬',
    frequency: 'daily2',
    items: [
      { id: 'esa-01', name: 'ソルアセトF（5本）',           standardStock: 5  },
      { id: 'esa-02', name: 'アセリオ1000mg',               standardStock: 5  },
      { id: 'esa-03', name: 'アタラックスP 25mg',           standardStock: 2  },
      { id: 'esa-04', name: 'カルバゾクロム 100mg',         standardStock: 2  },
      { id: 'esa-05', name: 'トラネキサム酸',               standardStock: 2  },
      { id: 'esa-06', name: 'ファモチジン',                 standardStock: 3  },
      { id: 'esa-07', name: 'ネオファーゲン20ml',           standardStock: 3  },
      { id: 'esa-08', name: 'ポララミン 5mg',               standardStock: 3  },
      { id: 'esa-09', name: 'ソル・メドロール 125mg',       standardStock: 3  },
      { id: 'esa-10', name: 'メトクロプラミド注',           standardStock: 5  },
      { id: 'esa-11', name: 'メイロン8.4% 20ml',            standardStock: 2  },
      { id: 'esa-12', name: 'フロセミド',                   standardStock: 2  },
      { id: 'esa-13', name: '50%ブドウ糖 20ml',             standardStock: 2  },
      { id: 'esa-14', name: '劇 ブスコパン注 20mg',         standardStock: 3  },
      { id: 'esa-15', name: '配置 生食 100ml',              standardStock: 5  },
      { id: 'esa-16', name: '配置 注射用蒸留水 20ml',       standardStock: 5  },
      { id: 'esa-17', name: '配置 生食 20ml',               standardStock: 5  },
      { id: 'esa-18', name: 'ケンエーGE120',                standardStock: 2  },
      { id: 'esa-19', name: 'ケンエーGE60',                 standardStock: 2  },
      { id: 'esa-20', name: '劇 ニフェジピン',              standardStock: 3  },
      { id: 'esa-21', name: '劇 ニトロペン',                standardStock: 3  },
      { id: 'esa-22', name: '劇 ボルタレン錠 25mg',         standardStock: 3  },
      { id: 'esa-23', name: 'カロナール',                   standardStock: 6  },
      { id: 'esa-24', name: 'ロキソプロフェン 60mg',        standardStock: 3  },
      { id: 'esa-25', name: '劇 破傷風トキソイドキット',    standardStock: 3  },
      { id: 'esa-26', name: '劇 ジクロフェナク座薬（50）',  standardStock: 3  },
      { id: 'esa-27', name: '劇 ジクロフェナク座薬（25）',  standardStock: 3  },
      { id: 'esa-28', name: 'ATP注',                        standardStock: 2  },
    ],
  },
  {
    id: 'cat-er-stock-b',
    name: '救命室ストック薬',
    frequency: 'daily2',
    items: [
      { id: 'esb-01', name: '生食 500ml',                   standardStock: 3  },
      { id: 'esb-02', name: '生食 100ml',                   standardStock: 3  },
      { id: 'esb-03', name: 'アセリオ1000mg',               standardStock: 5  },
      { id: 'esb-04', name: 'ソルデム1 500ml',              standardStock: 3  },
      { id: 'esb-05', name: 'ソルアセトF 500ml',            standardStock: 15 },
      { id: 'esb-06', name: '5%ブドウ糖 500ml',             standardStock: 1  },
      { id: 'esb-07', name: 'マンニトール 250ml',           standardStock: 2  },
      { id: 'esb-08', name: 'メイロン8.4% 250ml',           standardStock: 1  },
      { id: 'esb-09', name: 'ボルベン 500ml',               standardStock: 2  },
      { id: 'esb-10', name: 'ソルデム3A',                   standardStock: 1  },
      { id: 'esb-11', name: '劇 アドレナリン注シリンジ',    standardStock: 10 },
      { id: 'esb-12', name: '劇 ニカルジピン 2mg',          standardStock: 5  },
      { id: 'esb-13', name: '劇 ニカルジピン 10mg',         standardStock: 4  },
      { id: 'esb-14', name: '劇 ブチルスコポラミン',        standardStock: 3  },
      { id: 'esb-15', name: '劇 フルマゼニル',              standardStock: 2  },
      { id: 'esb-16', name: '劇 プロポフォール 50ml',       standardStock: 1  },
      { id: 'esb-17', name: 'アタラックスP 25mg',           standardStock: 2  },
      { id: 'esb-18', name: 'カルバゾクロム 100mg',         standardStock: 3  },
      { id: 'esb-19', name: 'ソル・メドロール 125mg',       standardStock: 3  },
      { id: 'esb-20', name: 'ニトロール',                   standardStock: 2  },
      { id: 'esb-21', name: 'メトクロプラミド注',           standardStock: 3  },
      { id: 'esb-22', name: 'ファモチジン',                 standardStock: 2  },
      { id: 'esb-23', name: '50%ブドウ糖 20ml',             standardStock: 1  },
      { id: 'esb-24', name: 'フロセミド',                   standardStock: 3  },
      { id: 'esb-25', name: 'トラネキサム酸',               standardStock: 3  },
      { id: 'esb-26', name: 'オメプラゾール 20mg',          standardStock: 2  },
      { id: 'esb-27', name: '配置 ヘパリン',                standardStock: 2  },
      { id: 'esb-28', name: '配置 生食 20ml',               standardStock: 5  },
      { id: 'esb-29', name: '配置 注射用蒸留水 20ml',       standardStock: 5  },
      { id: 'esb-30', name: '劇 ニトロペン',                standardStock: 1  },
      { id: 'esb-31', name: 'バイアスピリン（100）',        standardStock: 2  },
      { id: 'esb-32', name: 'エフィエント（20）',           standardStock: 1  },
      { id: 'esb-33', name: '劇 ミオコールスプレー',        standardStock: 1  },
    ],
  },
  {
    id: 'cat-er-teisu',
    name: 'ER定数物品',
    frequency: 'daily2',
    items: [
      { id: 'et-01', name: '体温計（救命1室）',             standardStock: 2  },
      { id: 'et-02', name: '体温計（救命2室）',             standardStock: 2  },
      { id: 'et-03', name: '体温計（救命3室）',             standardStock: 1  },
      { id: 'et-04', name: 'オキシメーター（救命1室）',     standardStock: 1  },
      { id: 'et-05', name: 'オキシメーター（救命2室）',     standardStock: 1  },
      { id: 'et-06', name: 'オキシメーター（救命3室）',     standardStock: 1  },
      { id: 'et-07', name: 'デキスター（救命1室）',         standardStock: 1  },
      { id: 'et-08', name: 'デキスター（救命2室）',         standardStock: 1  },
      { id: 'et-09', name: 'ペンライト',                    standardStock: 5  },
      { id: 'et-10', name: 'ストレッチャー点滴棒',          standardStock: 5  },
      { id: 'et-11', name: 'ネックカラー',                  standardStock: 3  },
      { id: 'et-12', name: '体温計（処置室）',              standardStock: 2  },
      { id: 'et-13', name: 'オキシメーター（処置室）',      standardStock: 1  },
      { id: 'et-14', name: 'デキスター（処置室）',          standardStock: 1  },
      { id: 'et-15', name: '点滴棒（処置室）',              standardStock: 5  },
    ],
  },
  {
    id: 'cat-er-steel',
    name: 'ER鋼製小物',
    frequency: 'daily2',
    items: [
      { id: 'es-01', name: '鑷子',                          standardStock: 20 },
      { id: 'es-02', name: '眼科用有鈎鑷子',                standardStock: 1  },
      { id: 'es-03', name: '眼科用無鈎鑷子',                standardStock: 3  },
      { id: 'es-04', name: '異物鑷子',                      standardStock: 3  },
      { id: 'es-05', name: 'セーレ',                        standardStock: 4  },
      { id: 'es-06', name: '眼科用セーレ（反）',            standardStock: 3  },
      { id: 'es-07', name: '眼科用セーレ（直）',            standardStock: 3  },
      { id: 'es-08', name: 'モスキートペアン',              standardStock: 1  },
      { id: 'es-09', name: 'モスキートコッヘル',            standardStock: 1  },
      { id: 'es-10', name: '持針器',                        standardStock: 3  },
      { id: 'es-11', name: 'ゾンデ',                        standardStock: 1  },
      { id: 'es-12', name: 'リムーバー',                    standardStock: 3  },
      { id: 'es-13', name: 'マダニ鑷子',                    standardStock: 1  },
      { id: 'es-14', name: 'マンドリン',                    standardStock: 1  },
      { id: 'es-15', name: '鼻鏡',                          standardStock: 2  },
      { id: 'es-16', name: 'バイオネット鑷子',              standardStock: 2  },
      { id: 'es-17', name: '吸引管',                        standardStock: 2  },
    ],
  },

  // ══════════════════════════════════════════════
  // 毎日1回（夜勤）: ER救急カート物品
  // ══════════════════════════════════════════════
  {
    id: 'cat-er-cart1',
    name: 'ER救急カート物品 1室（夜勤）',
    frequency: 'daily1',
    shiftFilter: ['night'],
    items: [
      { id: 'ec1-01', name: '留置針 20・22G',               standardStock: 2  },
      { id: 'ec1-02', name: '注射針 18G',                   standardStock: 3  },
      { id: 'ec1-03', name: '注射針 22G/23G',               standardStock: 2  },
      { id: 'ec1-04', name: '2.5cc注射器',                  standardStock: 3  },
      { id: 'ec1-05', name: '5cc注射器',                    standardStock: 2  },
      { id: 'ec1-06', name: '10cc注射器',                   standardStock: 2  },
      { id: 'ec1-07', name: '20cc注射器',                   standardStock: 2  },
      { id: 'ec1-08', name: '50cc注射器',                   standardStock: 2  },
      { id: 'ec1-09', name: '分注キット',                   standardStock: 1  },
      { id: 'ec1-10', name: '駆血帯',                       standardStock: 1  },
      { id: 'ec1-11', name: 'アルウェッティ',               standardStock: 1  },
      { id: 'ec1-12', name: 'エレバン 中',                  standardStock: 2  },
      { id: 'ec1-13', name: 'スピッツ（生化・血計）',       standardStock: 1  },
      { id: 'ec1-14', name: '喉頭鏡 3',                     standardStock: 1  },
      { id: 'ec1-15', name: '喉頭鏡 4',                     standardStock: 1  },
      { id: 'ec1-16', name: 'マギール鉗子',                 standardStock: 1  },
      { id: 'ec1-17', name: '舌鉗子/開口器',               standardStock: 1  },
      { id: 'ec1-18', name: 'バイドブロック 大・小',        standardStock: 1  },
      { id: 'ec1-19', name: 'カフ用注射器 10cc',            standardStock: 1  },
      { id: 'ec1-20', name: '布バン・トーマス',             standardStock: 1  },
      { id: 'ec1-21', name: '潤滑ゼリー',                   standardStock: 3  },
      { id: 'ec1-22', name: '経口挿管チューブ 7.0',         standardStock: 1  },
      { id: 'ec1-23', name: '経口挿管チューブ 7.5',         standardStock: 2  },
      { id: 'ec1-24', name: '経口挿管チューブ 8.0',         standardStock: 2  },
      { id: 'ec1-25', name: '経口挿管チューブ 8.5',         standardStock: 1  },
      { id: 'ec1-26', name: '経鼻エアウェイ 6・7・8',       standardStock: 1  },
      { id: 'ec1-27', name: 'ヤンカー',                     standardStock: 2  },
      { id: 'ec1-28', name: 'リザーバー酸素マスク',         standardStock: 1  },
      { id: 'ec1-29', name: '酸素マスク',                   standardStock: 1  },
      { id: 'ec1-30', name: '経鼻チューブ',                 standardStock: 1  },
      { id: 'ec1-31', name: '小児用ルート',                 standardStock: 2  },
      { id: 'ec1-32', name: 'スパイラルチューブ 7.0',       standardStock: 2  },
      { id: 'ec1-33', name: 'スパイラルチューブ 7.5',       standardStock: 3  },
      { id: 'ec1-34', name: 'スタイレット',                 standardStock: 4  },
      { id: 'ec1-35', name: 'クリニートラキアルチューブ 6.5', standardStock: 1 },
      { id: 'ec1-36', name: 'スパイラルマーフィー型 7.0',   standardStock: 1  },
      { id: 'ec1-37', name: 'I-gel ③',                      standardStock: 1  },
      { id: 'ec1-38', name: 'I-gel ④',                      standardStock: 1  },
    ],
  },
  {
    id: 'cat-er-cart2',
    name: 'ER救急カート物品 2室（夜勤）',
    frequency: 'daily1',
    shiftFilter: ['night'],
    items: [
      { id: 'ec2-01', name: '留置針 20・22G',               standardStock: 2  },
      { id: 'ec2-02', name: '注射針 22G/23G',               standardStock: 2  },
      { id: 'ec2-03', name: '2.5cc注射器',                  standardStock: 2  },
      { id: 'ec2-04', name: '5cc注射器',                    standardStock: 2  },
      { id: 'ec2-05', name: '10cc注射器',                   standardStock: 2  },
      { id: 'ec2-06', name: '20cc注射器',                   standardStock: 2  },
      { id: 'ec2-07', name: '分注キット',                   standardStock: 1  },
      { id: 'ec2-08', name: '駆血帯',                       standardStock: 2  },
      { id: 'ec2-09', name: 'アルウェッティ',               standardStock: 1  },
      { id: 'ec2-10', name: 'エレバン 中',                  standardStock: 2  },
      { id: 'ec2-11', name: 'スピッツ（生化・血計）',       standardStock: 1  },
      { id: 'ec2-12', name: 'ABGキット',                    standardStock: 3  },
      { id: 'ec2-13', name: '喉頭鏡 3',                     standardStock: 1  },
      { id: 'ec2-14', name: '喉頭鏡 4',                     standardStock: 1  },
      { id: 'ec2-15', name: 'マギール鉗子',                 standardStock: 1  },
      { id: 'ec2-16', name: '舌鉗子/開口器',               standardStock: 1  },
      { id: 'ec2-17', name: 'バイドブロック 大・小',        standardStock: 1  },
      { id: 'ec2-18', name: 'カフ用注射器 10cc',            standardStock: 1  },
      { id: 'ec2-19', name: '布バン・トーマス',             standardStock: 1  },
      { id: 'ec2-20', name: '潤滑ゼリー',                   standardStock: 3  },
      { id: 'ec2-21', name: '経口挿管チューブ 7.5',         standardStock: 2  },
      { id: 'ec2-22', name: '経口挿管チューブ 8.0',         standardStock: 2  },
      { id: 'ec2-23', name: '経鼻エアウェイ 6・7',          standardStock: 1  },
      { id: 'ec2-24', name: 'i-gel ③',                      standardStock: 1  },
      { id: 'ec2-25', name: 'i-gel ④',                      standardStock: 1  },
      { id: 'ec2-26', name: 'ヤンカー',                     standardStock: 2  },
      { id: 'ec2-27', name: '小児用ルート',                 standardStock: 2  },
    ],
  },

  // ══════════════════════════════════════════════
  // 毎日1回: カテ室関連
  // ══════════════════════════════════════════════
  {
    id: 'cat-karte-drug',
    name: 'カテ室救急カート薬品',
    frequency: 'daily1',
    items: [
      { id: 'kd-01', name: 'アドレナリン注シリンジ 1mg/1ml',  standardStock: 10 },
      { id: 'kd-02', name: 'アトロピン注シリンジ 0.5mg/1ml',  standardStock: 10 },
      { id: 'kd-03', name: 'カルチコール 425mg/5ml',          standardStock: 3  },
      { id: 'kd-04', name: 'ノルアドレナリン 1mg/1ml',        standardStock: 10 },
      { id: 'kd-05', name: 'ワソラン注 5mg/2ml',              standardStock: 2  },
      { id: 'kd-06', name: 'エフェドリン 40mg',               standardStock: 2  },
      { id: 'kd-07', name: '2%キシロカイン 100mg/5ml',        standardStock: 5  },
      { id: 'kd-08', name: 'メイロン２０ 20ml',               standardStock: 3  },
      { id: 'kd-09', name: 'ジギラノゲンC 0.4mg/3ml',         standardStock: 2  },
      { id: 'kd-10', name: 'ボスミン 1mg/1ml',                standardStock: 1  },
      { id: 'kd-11', name: '生理食塩液 20ml',                 standardStock: 5  },
      { id: 'kd-12', name: 'ソルアセトF 500ml',               standardStock: 1  },
      { id: 'kd-13', name: 'ソルデム1 500ml',                 standardStock: 1  },
      { id: 'kd-14', name: '塩酸ドパミンキット 200mg/200ml',  standardStock: 1  },
      { id: 'kd-15', name: 'メイロン250 250ml',               standardStock: 1  },
      { id: 'kd-16', name: '生食 100ml',                      standardStock: 1  },
    ],
  },
  {
    id: 'cat-stock1',
    name: 'カテ室ストック薬 1室',
    frequency: 'daily1',
    items: [
      { id: 's1-01', name: '生食（洗浄用）500ml',             standardStock: 8  },
      { id: 's1-02', name: '生食500ml',                       standardStock: 5  },
      { id: 's1-03', name: '生食100ml',                       standardStock: 1  },
      { id: 's1-04', name: 'ソルデム1 500ml',                 standardStock: 1  },
      { id: 's1-05', name: 'ソルアセトF 500ml',               standardStock: 1  },
      { id: 's1-06', name: 'エダラボン',                      standardStock: 1  },
      { id: 's1-07', name: '1%キシロカイン 10ml（劇）',       standardStock: 5  },
      { id: 's1-08', name: '1%キシロカイン 5ml（劇）',        standardStock: 5  },
      { id: 's1-09', name: 'ニカルジピン注射液（劇）',        standardStock: 2  },
      { id: 's1-10', name: '10%フェノバール（劇）',           standardStock: 2  },
      { id: 's1-11', name: 'メトクロプラミド',                standardStock: 2  },
      { id: 's1-12', name: 'ヘパリンNa注射液',                standardStock: 20 },
      { id: 's1-13', name: 'オザグレNa注射液',                standardStock: 1  },
      { id: 's1-14', name: 'ポピドンヨード外用液',            standardStock: 2  },
      { id: 's1-15', name: 'ハイポエタノール',                standardStock: 1  },
      { id: 's1-16', name: '挿管チューブ 経口7.5mm',          standardStock: 1  },
      { id: 's1-17', name: '挿管チューブ 経口8.0mm',          standardStock: 1  },
      { id: 's1-18', name: '挿管チューブ 経口8.5mm',          standardStock: 1  },
      { id: 's1-19', name: '劇 キシロカインスプレー',         standardStock: 1  },
      { id: 's1-20', name: 'バイトブロック 大（金具なし）',   standardStock: 1  },
      { id: 's1-21', name: 'バイトブロック 小（金具なし）',   standardStock: 1  },
      { id: 's1-22', name: '布バン 大',                       standardStock: 1  },
      { id: 's1-23', name: '布バン 小',                       standardStock: 1  },
      { id: 's1-24', name: 'カフ用注射器',                    standardStock: 2  },
      { id: 's1-25', name: '潤滑ゼリー',                      standardStock: 5  },
      { id: 's1-26', name: '喉頭鏡No.3',                      standardStock: 1  },
      { id: 's1-27', name: '喉頭鏡No.4',                      standardStock: 1  },
      { id: 's1-28', name: '開口器',                          standardStock: 1  },
      { id: 's1-29', name: 'マギール鉗子',                    standardStock: 1  },
      { id: 's1-30', name: 'トーマス',                        standardStock: 1  },
      { id: 's1-31', name: 'アンビュー',                      standardStock: 1  },
    ],
  },
  {
    id: 'cat-stock2',
    name: 'カテ室ストック薬 2室',
    frequency: 'daily1',
    items: [
      { id: 's2-01', name: '生食（洗浄用）500ml',             standardStock: 8  },
      { id: 's2-02', name: '生食1000ml',                      standardStock: 1  },
      { id: 's2-03', name: '生食500ml',                       standardStock: 5  },
      { id: 's2-04', name: '生食100ml',                       standardStock: 1  },
      { id: 's2-05', name: 'ソルデム1 500ml',                 standardStock: 2  },
      { id: 's2-06', name: 'ソルデム3A 500ml',                standardStock: 1  },
      { id: 's2-07', name: 'ソルアセトF 500ml',               standardStock: 2  },
      { id: 's2-08', name: '低分子デキストラン 500ml',        standardStock: 2  },
      { id: 's2-09', name: '1%キシロカイン 10ml（劇）',       standardStock: 5  },
      { id: 's2-10', name: '1%キシロカイン 5ml（劇）',        standardStock: 5  },
      { id: 's2-11', name: 'アトロピン硫酸塩注射液（劇）',    standardStock: 5  },
      { id: 's2-12', name: 'ニカルジピン注射液（劇）',        standardStock: 1  },
      { id: 's2-13', name: 'ソセゴン（劇）',                  standardStock: 4  },
      { id: 's2-14', name: 'ホリゾン',                        standardStock: 5  },
      { id: 's2-15', name: 'プロポフォール',                  standardStock: 1  },
      { id: 's2-16', name: 'アタラックスP',                   standardStock: 2  },
      { id: 's2-17', name: 'ソル・コーテフ 100mg',            standardStock: 3  },
      { id: 's2-18', name: 'ソル・メドロール 125mg',          standardStock: 1  },
      { id: 's2-19', name: 'メチルプレドニゾロン 500mg',      standardStock: 1  },
      { id: 's2-20', name: 'ネオシネジン',                    standardStock: 5  },
      { id: 's2-21', name: '劇 ドパミン塩酸塩 100mg/5ml',    standardStock: 3  },
      { id: 's2-22', name: '劇 ドブタミン塩酸塩 100mg/5ml',  standardStock: 3  },
      { id: 's2-23', name: 'ニトロール注',                    standardStock: 10 },
      { id: 's2-24', name: 'メトクロプラミド',                standardStock: 1  },
      { id: 's2-25', name: 'ヘパリンNa注射液',                standardStock: 20 },
      { id: 's2-26', name: '硫酸プロタミン',                  standardStock: 1  },
      { id: 's2-27', name: 'ニコランジル 2mg（冷所）',        standardStock: 3  },
      { id: 's2-28', name: '劇 バイアスピリン',               standardStock: 2  },
      { id: 's2-29', name: '劇 クロピドグレル',               standardStock: 4  },
      { id: 's2-30', name: '劇 エフィエント',                 standardStock: 1  },
      { id: 's2-31', name: 'スポンゼル',                      standardStock: 3  },
      { id: 's2-32', name: 'ポピドンヨード外用液',            standardStock: 3  },
      { id: 's2-33', name: 'ハイポエタノール',                standardStock: 1  },
    ],
  },
  {
    id: 'cat-karte-equip',
    name: 'カテ室救急カート物品',
    frequency: 'daily1',
    items: [
      { id: 'ke-01', name: '留置針 20・22G',                 standardStock: 2  },
      { id: 'ke-02', name: '注射針 22G/23G',                 standardStock: 2  },
      { id: 'ke-03', name: '注射針 18G',                     standardStock: 5  },
      { id: 'ke-04', name: '2.5cc注射器',                    standardStock: 2  },
      { id: 'ke-05', name: '5cc注射器',                      standardStock: 2  },
      { id: 'ke-06', name: '10cc注射器',                     standardStock: 2  },
      { id: 'ke-07', name: '20cc注射器',                     standardStock: 2  },
      { id: 'ke-08', name: '分注キット',                     standardStock: 1  },
      { id: 'ke-09', name: '駆血帯',                         standardStock: 1  },
      { id: 'ke-10', name: 'アルウェッティ',                 standardStock: 10 },
      { id: 'ke-11', name: 'エレバン 中',                    standardStock: 2  },
      { id: 'ke-12', name: 'スピッツ（生化・血計）',         standardStock: 1  },
      { id: 'ke-13', name: 'ABGキット',                      standardStock: 3  },
      { id: 'ke-14', name: 'チューシャバン',                 standardStock: 5  },
      { id: 'ke-15', name: '乾綿',                           standardStock: 5  },
      { id: 'ke-16', name: '喉頭鏡 3',                       standardStock: 1  },
      { id: 'ke-17', name: '喉頭鏡 4',                       standardStock: 1  },
      { id: 'ke-18', name: 'マギール鉗子',                   standardStock: 1  },
      { id: 'ke-19', name: '開口器',                         standardStock: 1  },
      { id: 'ke-20', name: '経鼻エアウェイ 6',              standardStock: 1  },
      { id: 'ke-21', name: 'バイドブロック 大・小',          standardStock: 1  },
      { id: 'ke-22', name: 'カフ用注射器 10cc',              standardStock: 2  },
      { id: 'ke-23', name: '布バン・トーマス',               standardStock: 1  },
      { id: 'ke-24', name: '潤滑ゼリー',                     standardStock: 3  },
      { id: 'ke-25', name: 'ペンライト',                     standardStock: 1  },
      { id: 'ke-26', name: '経口挿管チューブ 7.0',           standardStock: 1  },
      { id: 'ke-27', name: '経口挿管チューブ 7.5',           standardStock: 1  },
      { id: 'ke-28', name: '経口挿管チューブ 8.0',           standardStock: 1  },
      { id: 'ke-29', name: '小児用ルート',                   standardStock: 2  },
      { id: 'ke-30', name: 'オペ用ルート',                   standardStock: 2  },
      { id: 'ke-31', name: '輸液セット（三活2個付き）',      standardStock: 2  },
      { id: 'ke-32', name: '側注用ルート',                   standardStock: 2  },
      { id: 'ke-33', name: '輸血用ルート',                   standardStock: 2  },
      { id: 'ke-34', name: '延長ルート',                     standardStock: 2  },
      { id: 'ke-35', name: 'エコーカバー',                   standardStock: 3  },
      { id: 'ke-36', name: 'ガウン',                         standardStock: 3  },
      { id: 'ke-37', name: '袖なしエプロン',                 standardStock: 1  },
    ],
  },

  // ══════════════════════════════════════════════
  // 月1回
  // ══════════════════════════════════════════════
  {
    id: 'cat-cpa',
    name: 'CPAバッグ',
    frequency: 'monthly1',
    items: [
      { id: 'cpa-01', name: 'リザーバー・ネーゼル',          standardStock: 1  },
      { id: 'cpa-02', name: '吸引チューブ（サクション）',    standardStock: 1  },
      { id: 'cpa-03', name: '除細動パッド',                  standardStock: 2  },
      { id: 'cpa-04', name: 'セイラムサンプ・赤シリンジ',    standardStock: 1  },
      { id: 'cpa-05', name: '2.5ccシリンジ',                 standardStock: 5  },
      { id: 'cpa-06', name: '10ccシリンジ',                  standardStock: 3  },
      { id: 'cpa-07', name: '20ccシリンジ',                  standardStock: 2  },
      { id: 'cpa-08', name: '血圧計',                        standardStock: 1  },
      { id: 'cpa-09', name: '聴診器',                        standardStock: 1  },
      { id: 'cpa-10', name: 'ペンライト',                    standardStock: 1  },
      { id: 'cpa-11', name: 'イソジンボトル',                standardStock: 1  },
      { id: 'cpa-12', name: 'キープポア',                    standardStock: 1  },
      { id: 'cpa-13', name: '布テープ',                      standardStock: 1  },
      { id: 'cpa-14', name: 'アンビュー・マスク・チューブ',  standardStock: 1  },
      { id: 'cpa-15', name: 'ソルアセト',                    standardStock: 2  },
      { id: 'cpa-16', name: '塩酸ドパミン・小児ルート',      standardStock: 1  },
      { id: 'cpa-17', name: 'タイマー',                      standardStock: 1  },
      { id: 'cpa-18', name: 'デキスター',                    standardStock: 1  },
      { id: 'cpa-19', name: '注射針25G',                     standardStock: 3  },
      { id: 'cpa-20', name: '50%ブドウ糖 20ml',              standardStock: 1  },
      { id: 'cpa-21', name: 'ニトロール5mg',                 standardStock: 2  },
      { id: 'cpa-22', name: '生食20ml',                      standardStock: 2  },
      { id: 'cpa-23', name: 'メトクロプラミド10mg',          standardStock: 2  },
      { id: 'cpa-24', name: 'ミダゾラム10mg',                standardStock: 1  },
      { id: 'cpa-25', name: 'ホリゾン10mg',                  standardStock: 2  },
      { id: 'cpa-26', name: '劇 エホチール10mg',             standardStock: 2  },
      { id: 'cpa-27', name: '劇 ソセゴン15mg',               standardStock: 2  },
      { id: 'cpa-28', name: '劇 ニカルピン2mg',              standardStock: 2  },
      { id: 'cpa-29', name: 'アドレナリンシリンジ1mg',       standardStock: 10 },
      { id: 'cpa-30', name: '経口挿管 7.5・8.0',             standardStock: 2  },
      { id: 'cpa-31', name: '経鼻エアウェイ 6.0・7.0',       standardStock: 1  },
      { id: 'cpa-32', name: '喉頭鏡・ブレード（3・4）',      standardStock: 1  },
      { id: 'cpa-33', name: 'マギール鉗子',                  standardStock: 1  },
      { id: 'cpa-34', name: 'トーマス・バイドブロック',      standardStock: 1  },
      { id: 'cpa-35', name: 'キシロカインゼリー・スプレー',  standardStock: 1  },
      { id: 'cpa-36', name: '5ml赤シリンジ・布テープ',       standardStock: 1  },
      { id: 'cpa-37', name: '輸液セット（三活あり・なし）',  standardStock: 2  },
      { id: 'cpa-38', name: '造影ルート・側注ルート',        standardStock: 1  },
      { id: 'cpa-39', name: '三連三活・三活',                standardStock: 1  },
      { id: 'cpa-40', name: '駆血帯',                        standardStock: 2  },
      { id: 'cpa-41', name: 'アルコール綿',                  standardStock: 5  },
      { id: 'cpa-42', name: 'エレバン・チューシャバン（大）', standardStock: 5  },
      { id: 'cpa-43', name: 'サーフロ 20・22G',              standardStock: 3  },
      { id: 'cpa-44', name: 'サーフロ 18・24G',              standardStock: 2  },
      { id: 'cpa-45', name: '注射針 18・23G',                standardStock: 5  },
      { id: 'cpa-46', name: '手袋セット S・M',               standardStock: 1  },
    ],
  },
  {
    id: 'cat-trauma',
    name: '外傷バッグ',
    frequency: 'monthly1',
    items: [
      { id: 'tb-01', name: '（外ポケット右）ラベンダー手袋（M・S）', standardStock: 1 },
      { id: 'tb-02', name: '（外ポケット左）ハサミ（大・小）',       standardStock: 1 },
      { id: 'tb-03', name: '（正面）不潔ガーゼ',                     standardStock: 1 },
      { id: 'tb-04', name: '（正面）25G針・23G針',                   standardStock: 5 },
      { id: 'tb-05', name: '（正面）10ccシリンジ',                   standardStock: 5 },
      { id: 'tb-06', name: '（正面）N95マスク',                      standardStock: 2 },
      { id: 'tb-07', name: '（中）サバイバルシート',                  standardStock: 1 },
      { id: 'tb-08', name: '（中）フキシマル20cm幅',                  standardStock: 1 },
      { id: 'tb-09', name: '（中）ビニール（青）',                    standardStock: 1 },
      { id: 'tb-10', name: '（中）メス刃（NO. 11）',                  standardStock: 2 },
      { id: 'tb-11', name: '（中）潤滑ゼリー',                        standardStock: 1 },
      { id: 'tb-12', name: '（中）キシロカインポリアンプ',             standardStock: 2 },
      { id: 'tb-13', name: '（中）注射用水 20ml',                     standardStock: 2 },
      { id: 'tb-14', name: '（中）ネオヨジンゲル',                    standardStock: 1 },
      { id: 'tb-15', name: '（中）ウロバッグ',                        standardStock: 2 },
      { id: 'tb-16', name: '（ERより）SMAC（CVキット）',              standardStock: 1 },
      { id: 'tb-17', name: '（ERより）輪状甲状腺切開キット',          standardStock: 1 },
      { id: 'tb-18', name: '滅菌ガーゼ（10枚入り）',                  standardStock: 5 },
      { id: 'tb-19', name: '滅菌手袋（7・7.5）',                      standardStock: 2 },
      { id: 'tb-20', name: '（ERより）トロッカー20Frロング',           standardStock: 2 },
      { id: 'tb-21', name: 'イソジンボトル',                          standardStock: 2 },
      { id: 'tb-22', name: 'ソルアセトF500ml',                        standardStock: 2 },
      { id: 'tb-23', name: '輸液セット（三活付き）',                  standardStock: 2 },
      { id: 'tb-24', name: 'ベンリー帯',                              standardStock: 1 },
      { id: 'tb-25', name: 'ゲット（大・中）',                        standardStock: 3 },
      { id: 'tb-26', name: '駆血帯',                                  standardStock: 2 },
      { id: 'tb-27', name: 'アルコール綿',                            standardStock: 5 },
      { id: 'tb-28', name: 'サーフロロング（16G・18G）',              standardStock: 2 },
      { id: 'tb-29', name: '三活',                                    standardStock: 2 },
      { id: 'tb-30', name: 'キープポア',                              standardStock: 1 },
      { id: 'tb-31', name: '布テープ',                                standardStock: 1 },
    ],
  },
  {
    id: 'cat-heli',
    name: 'ヘリポート',
    frequency: 'monthly1',
    items: [
      { id: 'hp-01', name: 'ストレッチャー：正常に動くか',           standardStock: 1 },
      { id: 'hp-02', name: 'ストレッチャー：ストッパーは止まるか',   standardStock: 1 },
      { id: 'hp-03', name: '車椅子：正常に動くか',                   standardStock: 1 },
      { id: 'hp-04', name: '車椅子：ストッパーは止まるか',           standardStock: 1 },
      { id: 'hp-05', name: '酸素ボンベ：流量計は壊れていないか',     standardStock: 1 },
      { id: 'hp-06', name: '酸素ボンベ：酸素は入っているか',         standardStock: 1 },
      { id: 'hp-07', name: '用具：酸素マスク・チューブはあるか',     standardStock: 1 },
      { id: 'hp-08', name: '用具：タオルケットはあるか',             standardStock: 1 },
      { id: 'hp-09', name: '用具：掛け布団はあるか',                 standardStock: 1 },
      { id: 'hp-10', name: '用具：ソフィー（ピンク）はあるか',       standardStock: 1 },
      { id: 'hp-11', name: '用具：ディスポシーツはあるか',           standardStock: 1 },
    ],
  },
  {
    id: 'cat-peds',
    name: '小児セット',
    frequency: 'monthly1',
    items: [
      { id: 'pd-01', name: '①挿管チューブ 3.0',            standardStock: 1 },
      { id: 'pd-02', name: '挿管チューブ 3.5',              standardStock: 1 },
      { id: 'pd-03', name: 'マスク（3.0/3.5用）',           standardStock: 1 },
      { id: 'pd-04', name: '②挿管チューブ 4.0',            standardStock: 1 },
      { id: 'pd-05', name: 'マスク（4.0用）',               standardStock: 1 },
      { id: 'pd-06', name: '③挿管チューブ 4.5',            standardStock: 1 },
      { id: 'pd-07', name: 'マスク（4.5用）',               standardStock: 1 },
      { id: 'pd-08', name: '④挿管チューブ 5.0',            standardStock: 1 },
      { id: 'pd-09', name: 'マスク（5.0用）',               standardStock: 1 },
      { id: 'pd-10', name: '⑤挿管チューブ 5.5',            standardStock: 1 },
      { id: 'pd-11', name: 'マスク（5.5用）',               standardStock: 1 },
      { id: 'pd-12', name: '⑥挿管チューブ 6.0',            standardStock: 1 },
      { id: 'pd-13', name: '挿管チューブ 6.5',              standardStock: 1 },
      { id: 'pd-14', name: 'マスク（6.0/6.5用）',           standardStock: 1 },
      { id: 'pd-15', name: '⑦スタイレット',                standardStock: 3 },
      { id: 'pd-16', name: '吸引 5Fr・8Fr',                 standardStock: 2 },
      { id: 'pd-17', name: '骨髄穿刺キット',                standardStock: 2 },
      { id: 'pd-18', name: '⑧アンビュー（大）',            standardStock: 1 },
      { id: 'pd-19', name: 'アンビュー（小）',              standardStock: 1 },
      { id: 'pd-20', name: 'マスク（アンビュー用）',        standardStock: 6 },
      { id: 'pd-21', name: '⑨聴診器',                      standardStock: 2 },
      { id: 'pd-22', name: '小児血圧計',                    standardStock: 2 },
      { id: 'pd-23', name: 'マンシェット（大）',            standardStock: 2 },
      { id: 'pd-24', name: 'マンシェット5cm',               standardStock: 3 },
      { id: 'pd-25', name: 'マンシェット7cm',               standardStock: 2 },
      { id: 'pd-26', name: 'シーネ',                        standardStock: 4 },
      { id: 'pd-27', name: '⑩マンシェット10cm',            standardStock: 4 },
      { id: 'pd-28', name: 'マンシェット7cm（⑩）',         standardStock: 1 },
      { id: 'pd-29', name: 'SPO2（シール）',                standardStock: 1 },
    ],
  },

  // ══════════════════════════════════════════════
  // 月2回
  // ══════════════════════════════════════════════
  {
    id: 'cat-ambulance',
    name: '救急車',
    frequency: 'monthly2',
    items: [
      { id: 'am-01', name: '針刺しボックス',                standardStock: 1 },
      { id: 'am-02', name: 'ハサミ',                        standardStock: 1 },
      { id: 'am-03', name: 'ペンライト',                    standardStock: 1 },
      { id: 'am-04', name: 'タイマー',                      standardStock: 1 },
      { id: 'am-05', name: '滅菌ガーゼ（5枚・10枚）',      standardStock: 3 },
      { id: 'am-06', name: '輸液セット（三活付き・なし）',  standardStock: 1 },
      { id: 'am-07', name: '造影ルート',                    standardStock: 1 },
      { id: 'am-08', name: '三連三活',                      standardStock: 1 },
      { id: 'am-09', name: '駆血帯',                        standardStock: 1 },
      { id: 'am-10', name: 'サーフロ（22・20G）',           standardStock: 5 },
      { id: 'am-11', name: 'シリンジ（2.5・10・20ml）',     standardStock: 5 },
      { id: 'am-12', name: 'エレバン・アルコール綿',        standardStock: 5 },
      { id: 'am-13', name: 'キープポア',                    standardStock: 1 },
      { id: 'am-14', name: 'チュウーシャバン（大）',        standardStock: 1 },
      { id: 'am-15', name: '乾綿',                          standardStock: 1 },
      { id: 'am-16', name: 'アンビューバッグ',              standardStock: 1 },
      { id: 'am-17', name: '酸素ボンベ残量',                standardStock: 1 },
      { id: 'am-18', name: '酸素マスク・チューブ',          standardStock: 2 },
      { id: 'am-19', name: 'リザーバーマスク',              standardStock: 2 },
      { id: 'am-20', name: 'ネーゼル',                      standardStock: 2 },
      { id: 'am-21', name: '吸引チューブ・ヤンカー',        standardStock: 1 },
      { id: 'am-22', name: '手袋（M）',                     standardStock: 1 },
      { id: 'am-23', name: 'ティッシュ',                    standardStock: 1 },
      { id: 'am-24', name: 'モニター電極',                  standardStock: 1 },
      { id: 'am-25', name: 'サージカルマスク',              standardStock: 1 },
      { id: 'am-26', name: 'ゴミ箱の中を空にする',          standardStock: 1 },
    ],
  },
];
