import type { Category } from '../types';

export const DEFAULT_CATEGORIES: Category[] = [

  // ══════════════════════════════════════════════
  // 毎日2回（日勤・夜勤）: ER
  // ══════════════════════════════════════════════
  {
    id: 'cat-er-cart-drug1',
    name: '救急カート薬品 1室用（赤）',
    frequency: 'daily2',
    items: [
      { id: 'ecd1-01', name: 'ボスミン注 1mg/1ml',          standardStock: 5  },
      { id: 'ecd1-02', name: 'ドブタミン 100mg/5ml',        standardStock: 3  },
      { id: 'ecd1-03', name: 'ドパミン塩酸塩 100mg/5ml',    standardStock: 3  },
      { id: 'ecd1-04', name: 'ジギラノゲンC 0.4mg/2ml',     standardStock: 2  },
      { id: 'ecd1-05', name: 'アトロピン注 0.5mg/1ml',      standardStock: 6  },
      { id: 'ecd1-06', name: 'アドレナリン 1mg/1ml',        standardStock: 10 },
      { id: 'ecd1-07', name: 'エフェドリン 40mg/1ml',       standardStock: 1  },
      { id: 'ecd1-08', name: 'ワソラン注 5mg/2ml',          standardStock: 3  },
      { id: 'ecd1-09', name: 'ノルアドレナリン 1mg/1ml',    standardStock: 3  },
      { id: 'ecd1-10', name: 'サンリズム 50mg/5ml',         standardStock: 2  },
      { id: 'ecd1-11', name: 'キシロカイン２% 100mg/5ml',   standardStock: 5  },
      { id: 'ecd1-12', name: 'メイロン２０ 20ml',           standardStock: 2  },
    ],
  },
  {
    id: 'cat-er-cart-drug2',
    name: '救急カート薬品 2室用（ピンク）',
    frequency: 'daily2',
    items: [
      { id: 'ecd2-01', name: 'アドレナリン 1mg/1ml',        standardStock: 10 },
      { id: 'ecd2-02', name: 'プロタノールL注 0.2mg/1ml',   standardStock: 3  },
      { id: 'ecd2-03', name: 'アトロピン注 0.5mg/1ml',      standardStock: 5  },
      { id: 'ecd2-04', name: 'キシロカイン２% 100mg/5ml',   standardStock: 5  },
      { id: 'ecd2-05', name: 'ボスミン注 1mg/1ml',          standardStock: 5  },
      { id: 'ecd2-06', name: 'アトロピン硫酸塩 0.5mg/1ml',  standardStock: 5  },
      { id: 'ecd2-07', name: 'ワソラン注 5mg/2ml',          standardStock: 3  },
      { id: 'ecd2-08', name: 'フルマゼニル 0.5mg/5ml',      standardStock: 2  },
      { id: 'ecd2-09', name: '生理食塩液 20ml',             standardStock: 5  },
      { id: 'ecd2-10', name: 'ブチルスコポラミン 20mg/1ml', standardStock: 2  },
      { id: 'ecd2-11', name: 'フェノバール 100mg/1ml',      standardStock: 3  },
      { id: 'ecd2-12', name: 'ニカルジピン 2mg/2ml',        standardStock: 2  },
      { id: 'ecd2-13', name: 'ジギラノゲンC 0.4mg/2ml',     standardStock: 2  },
      { id: 'ecd2-14', name: 'カルチコール 8.5%/5ml',       standardStock: 3  },
      { id: 'ecd2-15', name: 'ネオシネジンコーワ 1ml',      standardStock: 1  },
    ],
  },
  {
    id: 'cat-er-stock-a',
    name: '処置室ストック薬',
    frequency: 'daily2',
    items: [
      { id: 'esa-01', name: 'ソルアセトF（5本）',       standardStock: 5  },
      { id: 'esa-02', name: 'アセリオ1000mg',           standardStock: 5  },
      { id: 'esa-03', name: 'アタラックスP 25mg',       standardStock: 2  },
      { id: 'esa-04', name: 'カルバゾクロム 100mg',     standardStock: 2  },
      { id: 'esa-05', name: 'トラネキサム酸',           standardStock: 2  },
      { id: 'esa-06', name: 'ファモチジン',             standardStock: 3  },
      { id: 'esa-07', name: 'ネオファーゲン20ml',       standardStock: 3  },
      { id: 'esa-08', name: 'ポララミン 5mg',           standardStock: 3  },
      { id: 'esa-09', name: 'ソル・メドロール 125mg',   standardStock: 3  },
      { id: 'esa-10', name: 'メトクロプラミド注',       standardStock: 5  },
      { id: 'esa-11', name: 'メイロン8.4% 20ml',        standardStock: 2  },
      { id: 'esa-12', name: 'フロセミド',               standardStock: 2  },
      { id: 'esa-13', name: '50%ブドウ糖 20ml',         standardStock: 2  },
      { id: 'esa-14', name: '劇 ブスコパン注 20mg',     standardStock: 3  },
      { id: 'esa-15', name: '配置 生食 100ml',          standardStock: 5  },
      { id: 'esa-16', name: '配置 注射用蒸留水 20ml',   standardStock: 5  },
      { id: 'esa-17', name: '配置 生食 20ml',           standardStock: 5  },
    ],
  },
  {
    id: 'cat-er-stock-b',
    name: '救命室ストック薬',
    frequency: 'daily2',
    items: [
      { id: 'esb-01', name: '生食 500ml',               standardStock: 3  },
      { id: 'esb-02', name: '生食 100ml',               standardStock: 3  },
      { id: 'esb-03', name: 'アセリオ1000mg',           standardStock: 5  },
      { id: 'esb-04', name: 'ソルデム1 500ml',          standardStock: 3  },
      { id: 'esb-05', name: 'ソルアセトF 500ml',        standardStock: 15 },
      { id: 'esb-06', name: '5%ブドウ糖 500ml',         standardStock: 1  },
      { id: 'esb-07', name: 'マンニトール 250ml',       standardStock: 2  },
      { id: 'esb-08', name: 'メイロン8.4% 250ml',       standardStock: 1  },
      { id: 'esb-09', name: 'ボルベン 500ml',           standardStock: 2  },
      { id: 'esb-10', name: 'ソルデム3A',               standardStock: 1  },
      { id: 'esb-11', name: '劇 アドレナリン注シリンジ', standardStock: 10 },
      { id: 'esb-12', name: '劇 ニカルジピン 2mg',      standardStock: 5  },
      { id: 'esb-13', name: '劇 ニカルジピン 10mg',     standardStock: 4  },
      { id: 'esb-14', name: '劇 ブチルスコポラミン',    standardStock: 3  },
      { id: 'esb-15', name: '劇 フルマゼニル',          standardStock: 2  },
      { id: 'esb-16', name: '劇 プロポフォール 50ml',   standardStock: 1  },
      { id: 'esb-17', name: 'アタラックスP 25mg',       standardStock: 2  },
      { id: 'esb-18', name: 'カルバゾクロム 100mg',     standardStock: 3  },
      { id: 'esb-19', name: 'ソル・メドロール 125mg',   standardStock: 3  },
      { id: 'esb-20', name: 'ニトロール',               standardStock: 3  },
    ],
  },
  {
    id: 'cat-er-teisu',
    name: 'ER定数物品',
    frequency: 'daily2',
    items: [
      // 救命室
      { id: 'et-01', name: '体温計（1室）',             standardStock: 2  },
      { id: 'et-02', name: '体温計（2室）',             standardStock: 2  },
      { id: 'et-03', name: '体温計（3室）',             standardStock: 1  },
      { id: 'et-04', name: 'オキシメーター（1室）',     standardStock: 1  },
      { id: 'et-05', name: 'オキシメーター（2室）',     standardStock: 1  },
      { id: 'et-06', name: 'オキシメーター（3室）',     standardStock: 1  },
      { id: 'et-07', name: 'デキスター（1室）',         standardStock: 1  },
      { id: 'et-08', name: 'デキスター（2室）',         standardStock: 1  },
      { id: 'et-09', name: 'ペンライト',                standardStock: 5  },
      { id: 'et-10', name: 'ストレッチャー点滴棒',      standardStock: 5  },
      { id: 'et-11', name: 'ネックカラー',              standardStock: 3  },
    ],
  },
  {
    id: 'cat-er-steel',
    name: 'ER鋼製小物',
    frequency: 'daily2',
    items: [
      { id: 'es-01', name: '鑷子',                      standardStock: 20 },
      { id: 'es-02', name: '眼科用有鈎鑷子',            standardStock: 1  },
      { id: 'es-03', name: '眼科用無鈎鑷子',            standardStock: 3  },
      { id: 'es-04', name: '異物鑷子',                  standardStock: 3  },
      { id: 'es-05', name: 'セーレ',                    standardStock: 4  },
      { id: 'es-06', name: '眼科用セーレ（反）',        standardStock: 3  },
      { id: 'es-07', name: '眼科用セーレ（直）',        standardStock: 3  },
      { id: 'es-08', name: 'モスキートペアン',          standardStock: 1  },
      { id: 'es-09', name: 'モスキートコッヘル',        standardStock: 1  },
      { id: 'es-10', name: '持針器',                    standardStock: 3  },
      { id: 'es-11', name: 'ゾンデ',                    standardStock: 1  },
      { id: 'es-12', name: 'リムーバー',                standardStock: 3  },
      { id: 'es-13', name: 'マダニ鑷子',                standardStock: 1  },
    ],
  },

  // ══════════════════════════════════════════════
  // 毎日1回: ER救急カート物品（夜勤帯チェック）
  // ══════════════════════════════════════════════
  {
    id: 'cat-er-cart1',
    name: 'ER救急カート物品 1室（夜勤）',
    frequency: 'daily1',
    shiftFilter: ['night'],
    items: [
      { id: 'ec1-01', name: '留置針 20・22G',           standardStock: 2  },
      { id: 'ec1-02', name: '注射針 18G',               standardStock: 3  },
      { id: 'ec1-03', name: '注射針 22G/23G',           standardStock: 2  },
      { id: 'ec1-04', name: '2.5cc注射器',              standardStock: 3  },
      { id: 'ec1-05', name: '5cc注射器',                standardStock: 2  },
      { id: 'ec1-06', name: '10cc注射器',               standardStock: 2  },
      { id: 'ec1-07', name: '20cc注射器',               standardStock: 2  },
      { id: 'ec1-08', name: '50cc注射器',               standardStock: 2  },
      { id: 'ec1-09', name: '分注キット',               standardStock: 1  },
      { id: 'ec1-10', name: '駆血帯',                   standardStock: 1  },
      { id: 'ec1-11', name: 'アルウェッティ',           standardStock: 1  },
      { id: 'ec1-12', name: 'エレバン 中',              standardStock: 2  },
      { id: 'ec1-13', name: 'スピッツ（生化・血計）',   standardStock: 1  },
      { id: 'ec1-14', name: '喉頭鏡 3',                 standardStock: 1  },
      { id: 'ec1-15', name: '喉頭鏡 4',                 standardStock: 1  },
      { id: 'ec1-16', name: 'マギール鉗子',             standardStock: 1  },
      { id: 'ec1-17', name: '舌鈕子/開口器',            standardStock: 1  },
      { id: 'ec1-18', name: 'バイドブロック 大・小',    standardStock: 1  },
      { id: 'ec1-19', name: 'カフ用注射器 10cc',        standardStock: 1  },
      { id: 'ec1-20', name: '布バン・トーマス',         standardStock: 1  },
      { id: 'ec1-21', name: '潤滑ゼリー',               standardStock: 3  },
    ],
  },
  {
    id: 'cat-er-cart2',
    name: 'ER救急カート物品 2室（夜勤）',
    frequency: 'daily1',
    shiftFilter: ['night'],
    items: [
      { id: 'ec2-01', name: '留置針 20・22G',           standardStock: 2  },
      { id: 'ec2-02', name: '注射針 22G/23G',           standardStock: 2  },
      { id: 'ec2-03', name: '2.5cc注射器',              standardStock: 2  },
      { id: 'ec2-04', name: '5cc注射器',                standardStock: 2  },
      { id: 'ec2-05', name: '10cc注射器',               standardStock: 2  },
      { id: 'ec2-06', name: '20cc注射器',               standardStock: 2  },
      { id: 'ec2-07', name: '分注キット',               standardStock: 1  },
      { id: 'ec2-08', name: '駆血帯',                   standardStock: 2  },
      { id: 'ec2-09', name: 'アルウェッティ',           standardStock: 1  },
      { id: 'ec2-10', name: 'エレバン 中',              standardStock: 2  },
      { id: 'ec2-11', name: 'スピッツ（生化・血計）',   standardStock: 1  },
      { id: 'ec2-12', name: 'ABGキット',                standardStock: 3  },
      { id: 'ec2-13', name: '喉頭鏡 3',                 standardStock: 1  },
      { id: 'ec2-14', name: '喉頭鏡 4',                 standardStock: 1  },
      { id: 'ec2-15', name: 'マギール鉗子',             standardStock: 1  },
      { id: 'ec2-16', name: '舌鈕子/開口器',            standardStock: 1  },
      { id: 'ec2-17', name: 'バイドブロック 大・小',    standardStock: 1  },
      { id: 'ec2-18', name: 'カフ用注射器 10cc',        standardStock: 1  },
      { id: 'ec2-19', name: '布バン・トーマス',         standardStock: 1  },
      { id: 'ec2-20', name: '潤滑ゼリー',               standardStock: 3  },
    ],
  },

  // ══════════════════════════════════════════════
  // 毎日1回: カテ室関連
  // ══════════════════════════════════════════════
  {
    id: 'cat-karte-drug',
    name: 'カテ室救急カート薬品',
    frequency: 'daily1',
    items: [
      { id: 'kd-01', name: 'アドレナリン注シリンジ 1mg/1ml',  standardStock: 10 },
      { id: 'kd-02', name: 'アトロピン注シリンジ 0.5mg/1ml', standardStock: 10 },
      { id: 'kd-03', name: 'カルチコール 425mg/5ml',          standardStock: 3  },
      { id: 'kd-04', name: 'ノルアドレナリン 1mg/1ml',        standardStock: 10 },
      { id: 'kd-05', name: 'ワソラン注 5mg/2ml',              standardStock: 2  },
      { id: 'kd-06', name: 'エフェドリン 40mg',               standardStock: 2  },
      { id: 'kd-07', name: '2%キシロカイン 100mg/5ml',        standardStock: 5  },
      { id: 'kd-08', name: 'メイロン２０ 20ml',               standardStock: 3  },
      { id: 'kd-09', name: 'ジギラノゲンC 0.4mg/3ml',         standardStock: 2  },
      { id: 'kd-10', name: 'ボスミン 1mg/1ml',                standardStock: 1  },
      { id: 'kd-11', name: '生理食塩液 20ml',                 standardStock: 5  },
    ],
  },
  {
    id: 'cat-stock1',
    name: 'カテ室ストック薬 1室',
    frequency: 'daily1',
    items: [
      { id: 's1-01', name: '生食（洗浄用）500ml',       standardStock: 8  },
      { id: 's1-02', name: '生食500ml',                 standardStock: 5  },
      { id: 's1-03', name: '生食100ml',                 standardStock: 1  },
      { id: 's1-04', name: 'ソルデム1 500ml',           standardStock: 1  },
      { id: 's1-05', name: 'ソルアセトF 500ml',         standardStock: 1  },
      { id: 's1-06', name: 'エダラボン',                standardStock: 1  },
      { id: 's1-07', name: '1%キシロカイン 10ml（劇）', standardStock: 5  },
      { id: 's1-08', name: '1%キシロカイン 5ml（劇）',  standardStock: 5  },
      { id: 's1-09', name: 'ニカルジピン注射液（劇）',  standardStock: 2  },
      { id: 's1-10', name: '10%フェノバール（劇）',     standardStock: 2  },
      { id: 's1-11', name: 'メトクロプラミド',          standardStock: 2  },
      { id: 's1-12', name: 'ヘパリンNa注射液',          standardStock: 20 },
      { id: 's1-13', name: 'オザグレNa注射液',          standardStock: 1  },
      { id: 's1-14', name: 'ポピドンヨード外用液',      standardStock: 2  },
      { id: 's1-15', name: 'ハイポエタノール',          standardStock: 1  },
    ],
  },
  {
    id: 'cat-stock2',
    name: 'カテ室ストック薬 2室',
    frequency: 'daily1',
    items: [
      { id: 's2-01', name: '生食（洗浄用）500ml',           standardStock: 8  },
      { id: 's2-02', name: '生食1000ml',                    standardStock: 1  },
      { id: 's2-03', name: '生食500ml',                     standardStock: 5  },
      { id: 's2-04', name: '生食100ml',                     standardStock: 1  },
      { id: 's2-05', name: 'ソルデム1 500ml',               standardStock: 2  },
      { id: 's2-06', name: 'ソルデム3A 500ml',              standardStock: 1  },
      { id: 's2-07', name: 'ソルアセトF 500ml',             standardStock: 2  },
      { id: 's2-08', name: '低分子デキストラン 500ml',      standardStock: 2  },
      { id: 's2-09', name: '1%キシロカイン 10ml（劇）',     standardStock: 5  },
      { id: 's2-10', name: '1%キシロカイン 5ml（劇）',      standardStock: 5  },
      { id: 's2-11', name: 'アトロピン硫酸塩注射液（劇）',  standardStock: 5  },
      { id: 's2-12', name: 'ニカルジピン注射液（劇）',      standardStock: 1  },
      { id: 's2-13', name: 'ソセゴン（劇）',                standardStock: 4  },
      { id: 's2-14', name: 'ホリゾン',                      standardStock: 5  },
      { id: 's2-15', name: 'プロポフォール',                standardStock: 1  },
      { id: 's2-16', name: 'アタラックスP',                 standardStock: 2  },
      { id: 's2-17', name: 'ソル・コーテフ 100mg',          standardStock: 3  },
      { id: 's2-18', name: 'ソル・メドロール 125mg',        standardStock: 1  },
      { id: 's2-19', name: 'メチルプレドニゾロン 500mg',    standardStock: 1  },
      { id: 's2-20', name: 'ネオシネジン',                  standardStock: 5  },
    ],
  },
  {
    id: 'cat-karte-equip',
    name: 'カテ室救急カート物品',
    frequency: 'daily1',
    items: [
      { id: 'ke-01', name: '留置針 20・22G',            standardStock: 2  },
      { id: 'ke-02', name: '注射針 22G/23G',            standardStock: 2  },
      { id: 'ke-03', name: '注射針 18G',                standardStock: 5  },
      { id: 'ke-04', name: '2.5cc注射器',               standardStock: 2  },
      { id: 'ke-05', name: '5cc注射器',                 standardStock: 2  },
      { id: 'ke-06', name: '10cc注射器',                standardStock: 2  },
      { id: 'ke-07', name: '20cc注射器',                standardStock: 2  },
      { id: 'ke-08', name: '分注キット',                standardStock: 1  },
      { id: 'ke-09', name: '駆血帯',                    standardStock: 1  },
      { id: 'ke-10', name: 'アルウェッティ',            standardStock: 10 },
      { id: 'ke-11', name: 'エレバン 中',               standardStock: 2  },
      { id: 'ke-12', name: 'スピッツ（生化・血計）',    standardStock: 1  },
      { id: 'ke-13', name: 'ABGキット',                 standardStock: 3  },
      { id: 'ke-14', name: 'チューシャバン',            standardStock: 5  },
      { id: 'ke-15', name: '乾綿',                      standardStock: 5  },
      { id: 'ke-16', name: '喉頭鏡 3',                  standardStock: 1  },
      { id: 'ke-17', name: '喉頭鏡 4',                  standardStock: 1  },
      { id: 'ke-18', name: 'マギール鉗子',              standardStock: 1  },
      { id: 'ke-19', name: '開口器',                    standardStock: 1  },
      { id: 'ke-20', name: '経鼻エアウェイ 6',          standardStock: 1  },
    ],
  },

  // ══════════════════════════════════════════════
  // 月1回
  // ══════════════════════════════════════════════
  {
    id: 'cat-cpa',
    name: 'CPAバッグ',
    frequency: 'monthly1',
    items: [
      { id: 'cpa-01', name: 'リザーバー・ネーゼル',         standardStock: 1 },
      { id: 'cpa-02', name: '吸引チューブ（サクション）',   standardStock: 1 },
      { id: 'cpa-03', name: '除細動パッド',                 standardStock: 2 },
      { id: 'cpa-04', name: 'セイラムサンプ・赤シリンジ',   standardStock: 1 },
      { id: 'cpa-05', name: '2.5ccシリンジ',                standardStock: 5 },
      { id: 'cpa-06', name: '10ccシリンジ',                 standardStock: 3 },
      { id: 'cpa-07', name: '20ccシリンジ',                 standardStock: 2 },
      { id: 'cpa-08', name: '血圧計',                       standardStock: 1 },
      { id: 'cpa-09', name: '聴診器',                       standardStock: 1 },
      { id: 'cpa-10', name: 'ペンライト',                   standardStock: 1 },
      { id: 'cpa-11', name: 'イソジンボトル',               standardStock: 1 },
      { id: 'cpa-12', name: 'キープポア',                   standardStock: 1 },
      { id: 'cpa-13', name: '布テープ',                     standardStock: 1 },
      { id: 'cpa-14', name: 'アンビュー・マスク・チューブ', standardStock: 1 },
      { id: 'cpa-15', name: 'ソルアセト',                   standardStock: 2 },
      { id: 'cpa-16', name: '塩酸ドパミン・小児ルート',     standardStock: 1 },
      { id: 'cpa-17', name: 'タイマー',                     standardStock: 1 },
      { id: 'cpa-18', name: 'デキスター',                   standardStock: 1 },
      { id: 'cpa-19', name: '注射針25G',                    standardStock: 3 },
    ],
  },
  {
    id: 'cat-trauma',
    name: '外傷バッグ',
    frequency: 'monthly1',
    items: [
      { id: 'tb-01', name: '（外ポケット右）ラベンダー手袋（M・S）', standardStock: 1 },
      { id: 'tb-02', name: '（外ポケット左）ハサミ（大・小）',       standardStock: 1 },
      { id: 'tb-03', name: '（正面）不潔ガーゼ',                     standardStock: 1 },
      { id: 'tb-04', name: '（正面）25G針・23G針',                   standardStock: 5 },
      { id: 'tb-05', name: '（正面）10ccシリンジ',                   standardStock: 5 },
      { id: 'tb-06', name: '（正面）N95マスク',                      standardStock: 2 },
      { id: 'tb-07', name: '（中）サバイバルシート',                  standardStock: 1 },
      { id: 'tb-08', name: '（中）フキシマル20cm幅',                  standardStock: 1 },
      { id: 'tb-09', name: '（中）ビニール（青）',                    standardStock: 1 },
      { id: 'tb-10', name: '（中）メス刃（NO. 11）',                  standardStock: 2 },
      { id: 'tb-11', name: '（中）潤滑ゼリー',                        standardStock: 1 },
      { id: 'tb-12', name: '（中）キシロカインポリアンプ',             standardStock: 2 },
      { id: 'tb-13', name: '（中）注射用水 20ml',                     standardStock: 2 },
      { id: 'tb-14', name: '（中）ネオヨジンゲル',                    standardStock: 1 },
      { id: 'tb-15', name: '（中）ウロバッグ',                        standardStock: 2 },
      { id: 'tb-16', name: '（ERより）SMAC（CVキット）',              standardStock: 1 },
    ],
  },
  {
    id: 'cat-heli',
    name: 'ヘリポート',
    frequency: 'monthly1',
    items: [
      { id: 'hp-01', name: 'ストレッチャー：正常に動くか',         standardStock: 1 },
      { id: 'hp-02', name: 'ストレッチャー：ストッパーは止まるか', standardStock: 1 },
      { id: 'hp-03', name: '車椅子：正常に動くか',                 standardStock: 1 },
      { id: 'hp-04', name: '車椅子：ストッパーは止まるか',         standardStock: 1 },
      { id: 'hp-05', name: '酸素ボンベ：流量計は壊れていないか',   standardStock: 1 },
      { id: 'hp-06', name: '酸素ボンベ：酸素は入っているか',       standardStock: 1 },
      { id: 'hp-07', name: '用具：酸素マスク・チューブはあるか',   standardStock: 1 },
    ],
  },
  {
    id: 'cat-peds',
    name: '小児セット',
    frequency: 'monthly1',
    items: [
      { id: 'pd-01', name: '①挿管チューブ 3.0', standardStock: 1 },
      { id: 'pd-02', name: '①マスク（3.0用）',  standardStock: 1 },
      { id: 'pd-03', name: '②挿管チューブ 4.0', standardStock: 1 },
      { id: 'pd-04', name: '②マスク（4.0用）',  standardStock: 1 },
      { id: 'pd-05', name: '③挿管チューブ 4.5', standardStock: 1 },
      { id: 'pd-06', name: '③マスク（4.5用）',  standardStock: 1 },
      { id: 'pd-07', name: '④挿管チューブ 5.0', standardStock: 1 },
      { id: 'pd-08', name: '④マスク（5.0用）',  standardStock: 1 },
      { id: 'pd-09', name: '⑤挿管チューブ 5.5', standardStock: 1 },
      { id: 'pd-10', name: '⑤マスク（5.5用）',  standardStock: 1 },
      { id: 'pd-11', name: '⑥挿管チューブ 6.0', standardStock: 1 },
      { id: 'pd-12', name: '挿管チューブ 6.5',   standardStock: 1 },
    ],
  },

  // ══════════════════════════════════════════════
  // 月2回
  // ══════════════════════════════════════════════
  {
    id: 'cat-ambulance',
    name: '救急車',
    frequency: 'monthly2',
    items: [
      { id: 'am-01', name: '針刺しボックス',               standardStock: 1 },
      { id: 'am-02', name: 'ハサミ',                       standardStock: 1 },
      { id: 'am-03', name: 'ペンライト',                   standardStock: 1 },
      { id: 'am-04', name: 'タイマー',                     standardStock: 1 },
      { id: 'am-05', name: '滅菌ガーゼ（5枚・10枚）',     standardStock: 3 },
      { id: 'am-06', name: '輸液セット（三活付き・なし）', standardStock: 1 },
      { id: 'am-07', name: '造影ルート',                   standardStock: 1 },
      { id: 'am-08', name: '三連三活',                     standardStock: 1 },
      { id: 'am-09', name: '駆血帯',                       standardStock: 1 },
      { id: 'am-10', name: 'サーフロ（22・20G）',          standardStock: 5 },
      { id: 'am-11', name: 'シリンジ（2.5・10・20ml）',    standardStock: 5 },
      { id: 'am-12', name: 'エレバン・アルコール綿',       standardStock: 5 },
      { id: 'am-13', name: 'キープポア',                   standardStock: 1 },
    ],
  },
];
